# © 2024 by Rowan Ackerman
# All parts of this and other files in this repository not autogenerated
# are under the copyright of Rowan Ackerman.

all: unexecutable pull executable

unexecutable: redirect.py
	chmod -x redirect.py

executable: redirect.py
	chmod +x redirect.py

pull:
	git pull
